apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: react-frontend:v17 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"          
          limits:
            cpu: "500m"
            memory: "1024Mi"
